#!/usr/bin/env bash
# Transfers a file from our client to a server
# "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
# transfer the file to the user `scp` home directory `~/`

FILEPATH=$1
IP=$2
USER=$3
PRIVATE_KEY=$4

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking="no" -i "$PRIVATE_KEY" "$FILEPATH" scp://"$USER"@"$IP"/~
fi
