#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements
# /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

apt-get -y update
apt-get -y install nginx
new_string="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "\@^\s*location / {@s@^@$new_string@" /etc/nginx/sites-available/default
service nginx restart
