#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements

# install nginx
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
# Configure your Nginx server to have "Hello World!" page
echo "Hello World!" > /var/www/html/index*html
# make a custom 404 file
echo "Ceci n'est pas une page" > /var/www/html/custom404.html

# delete the default link from sites-enabled
rm /etc/nginx/site-enabled/default

# create a new conf file
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	add_header X-Served-By $HOSTNAME

	location /redirect_me {
                return 301 https://github.com/Mostafa1Jamal1;
        }

	error_page 404 /custom404.html;
        location = /custom404.html {
                internal;
        }

	location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }

}" > /etc/nginx/sites-available/new_default
ln -s /etc/nginx/sites-available/new_default /etc/nginx/sites-enabled/
# restart the service
service nginx start
service nginx restart
