#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# 1- Update the OS
apt-get update
apt-get upgrade -y

# 2- Install HAproxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get install haproxy=2.8.\* -y
apt update && apt upgrade -y #again

# 3- Configure HAproxy

## save a copy of the default configration
cp -a /etc/haproxy/haproxy.cfg{,.original}

## Make sure that HAproxy can be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy

## edit the configuration file
echo "
frontend mostafa-frontend
	bind *:80
	mode http
	default_backend mostafa-backend

backend mostafa-backend
	balance roundrobin
	server web-01 54.157.131.239
	server web-02 34.202.157.240
" >> /etc/haproxy/haproxy.cfg

## restart HAproxy
service haproxy restart
