#!/usr/bin/env bash
# configures a server to make Nginx running,
# and listening on port 80 of all the server’s active IPv4 IPs

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start
