#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pgrep -n | cat > /var/run/myscript.pid

trap "echo 'I hate the kill command' && rm /var/run/myscript.pid && exit" 15
trap "echo 'Y U no love me?!' && exit" SIGINT
trap "rm /var/run/myscript.pid && exit" SIGQUIT

while (( 1 )); do
	echo "To infinity and beyond"
	sleep 2
done
