#!/usr/bin/env bash
# displays Best School 10 times.
# but for the 9th iteration, displays Best School and then Hi on a new line
# Using the while loop
x=0
while (( x < 10 )); do
	echo "Best School"
	if [ "$x" -eq 8 ]
	then
		echo "Hi"
	fi
	(( x++ ))
done
