#!/usr/bin/env bash
# displays Best School 10 times.
# but for the 9th iteration, displays Best School and then Hi on a new line
# Using the while loop
x=1
while (( x <= 10 )); do
	if [ "$x" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$x" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
