#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
minutes=1
echo "Hour: $hour"
while (( hour < 12 )); do
	if (( minutes > 59 ))
	then
		(( hour++ ))
		minutes=1
		echo "Hour: $hour"
	else
		echo "$minutes"
		(( minutes++ ))
	fi
done
echo "Hour: $hour"
