#!/usr/bin/env bash
# make nginx run as nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo service apache2 stop
sudo sed -i '/user/ s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '/listen .*80 /s/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo su -c '/etc/init.d/nginx start' nginx
