#!/usr/bin/env bash
# make nginx run as nginx user
pkill apache2
sudo chmod 666 /etc/nginx/nginx.conf
sudo sed -i '/[ :]80 default_server/s/80/8080/' /etc/nginx/sites-enabled/default
sudo sed -i '/user/ s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
